version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: perfectme-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: perfectme
      MYSQL_USER: perfectme
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: perfectme-backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: perfectme
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
    command: npm start

  frontend:
    build: ./frontend
    container_name: perfectme-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001

volumes:
  mysql_data: